threads: 6
buckets: 128
buckets3: 128
farmerKey: YOUR FARMER KEY
poolKey: YOUR POOL KEY
tmpDir: YOUR TEMP FOLDER
tmpDir2: YOUR TEMPORARY DIRECTORY 2 RAMDISK
finalDir:
- HDD 1 (just Letter)
- HDD 2 (just Letter)
tmpToggle: false
chiaPlotterLoc: YOUR MADMAX FOLDER
logs: false
logDir: YOUR LOG CREATOR FOLDER
logsMoved: false
logDirMoved: YOUR LOG MOVER FOLDER