# chia_plot [OPTION...]

# -r, --threads arg     | Number of threads (default = 4)
threads: 6
# -u, --buckets arg     | Number of buckets (default = 256)
buckets: 256
# -v, --buckets3 arg    | Number of buckets for phase 3+4 (default = buckets)
buckets3: 256
# -f, --farmerkey arg   | Your farmer key (48 bytes)
farmerKey: 1234sf56579vfsd846976164458712348
# -p, --poolkey arg     | Your pool key (48 bytes) | not used, use pool contract now
#poolKey: 1234sf56579vfsd846976164458712348ssqrzfqsgsqd
# -c, --contract arg    | Pool Contract Address (64 chars)
poolContract: xchqdqfdqf532434315638
# -t, --tmpdir arg      | Your temporary path
tmpDir: H:\
# -2, --tmpdir2 arg     | Your temporary directory 2 or RAMDISK or nothing
tmpDir2: 
# -d, --finaldir arg    | Optianal : Your Final disk letters for .plot, default is tmpDir directory
finalDir:
- E:\
- G:\MyPool
- F:\
- D:\AnotherPool
# Your madMax path
chiaPlotterLoc: C:\Crypto\madMax v0.1.1
# Enable creating log   | true/false
logs: false
# Enable moving log     | true/false
logsMoved: false
# -G, --tmptoggle       | Enable tmptoggle | Alternate tmpDir/tmpDir2 (default = false)
tmpToggle: false
