# chia_plot [OPTION...]

# -n, --count arg      Number of plots to create (default = 1, -1 = infinite)
# -r, --threads arg    Number of threads (default = 4)
# -u, --buckets arg    Number of buckets (default = 256)
# -v, --buckets3 arg   Number of buckets for phase 3+4 (default = buckets)
# -t, --tmpdir arg     Temporary directory, needs ~220 GiB (default = $PWD)
# -2, --tmpdir2 arg    Temporary directory 2, needs ~110 GiB [RAM] (default = <tmpdir>)
# -d, --finaldir arg   Final directory (default = <tmpdir>)
# -p, --poolkey arg    Pool Public Key (48 bytes)
# -f, --farmerkey arg  Farmer Public Key (48 bytes)
# -G, --tmptoggle      Alternate tmpdir/tmpdir2 (default = false)

threads: 6
buckets: 128
buckets3: 128
farmerKey: YOUR FARMER KEY
poolKey: YOUR POOL KEY
tmpDir: YOUR TEMP FOLDER
tmpDir2: YOUR TEMPORARY DIRECTORY 2 RAMDISK
finalDir:
- HDD 1 (just Letter)
- HDD 2 (just Letter)
tmpToggle: false
chiaPlotterLoc: YOUR MADMAX FOLDER
logs: false
logsMoved: false
logDir: YOUR LOG CREATOR FOLDER